spring:
  application:
    name: mq
  rabbitmq:
    host: 172.16.250.129
    port: 5672
    username: guest
    password: guest
    virtual-host: /ems
#    手动ack
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
server:
  port: 8002